### ISSUE TITLE
Missing Pygments dependency  for OSX

### ISSUE THREAD

**Issue by salex** [Bodacious/blogit#27]
Tried to install blogit on a new bare application (only user)

I added the first post with a code block and it spews out the error listed below. Only search I could find talked about installing Pygments. After a little more searching, I found the fix for Mac OSX

```
sudo easy_install Pygments
```

Just though you'd want to add it to your notes. Apparently Albino does not look for the package. Now I just have to figure out why no css.

The error for your reference:

```
No such file or directory - posix_spawnp
Extracted source (around line #1):

1: <%= format_content(post.body) %>
Trace of template inclusion: /Users/salex/.rvm/gems/ruby-1.9.3-p327/gems/blogit-0.7.0/app/views/blogit/posts/_post.html.erb, /Users/salex/.rvm/gems/ruby-1.9.3-p327/gems/blogit-0.7.0/app/views/blogit/posts/index.html.erb

Rails.root: /Users/salex/work/salex

Application Trace | Framework Trace | Full Trace
posix-spawn (0.3.6) lib/posix/spawn.rb:187:in `_pspawn'
posix-spawn (0.3.6) lib/posix/spawn.rb:187:in `pspawn'

posix-spawn (0.3.6) lib/posix/spawn.rb:160:in `spawn'
posix-spawn (0.3.6) lib/posix/spawn.rb:307:in `popen4'
posix-spawn (0.3.6) lib/posix/spawn/child.rb:105:in `exec!'
posix-spawn (0.3.6) lib/posix/spawn/child.rb:80:in `initialize'
albino (1.3.3) lib/albino.rb:87:in `new'
albino (1.3.3) lib/albino.rb:87:in `execute'
albino (1.3.3) lib/albino.rb:91:in `colorize'
albino (1.3.3) lib/albino.rb:73:in `colorize'
blogit (0.7.0) lib/blogit/renderers/html_with_albino.rb:5:in `block_code'
blogit (0.7.0) lib/blogit/parsers/markdown_parser.rb:14:in `render'
blogit (0.7.0) lib/blogit/parsers/markdown_parser.rb:14:in `parsed'
blogit (0.7.0) app/helpers/blogit/application_helper.rb:28:in `format_content'
blogit (0.7.0) app/views/blogit/posts/_post_body.html.erb:1:in `___sers_salex__rvm_gems_ruby_______p____gems_blogit_______app_views_blogit_posts__post_body_html_erb__473769633676305497_2163340860'
```

**Comment by Bodacious** [comment]
@salex - sorry for taking so long to get back to you on this.

Thanks for raising the issue -I'll add a check to ensure pygments is installed for those using the markdown parser.

**Comment by Bodacious** [comment]
I've added a warning message to be raised if trying to use the markdown parser with code syntax highlighting and pygments is not installed.

I've also added a CSS file which you can include in your app - check #32
