### ISSUE TITLE
rails generate fails

### ISSUE THREAD

**Issue by mices** [Bodacious/blogit#95]
I couldn't get this to work with any rails version Have you considered upgrading it

**Comment by Bodacious** [comment]
Yes, we're working on a new major version now. This should be available in February.

What are the problems you're having just now?

**Comment by mices** [comment]
Couldn't complete bundle install

**Comment by mices** [comment]
Here's what happens with rails 5.1 
/.rvm/gems/ruby-2.3.3/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:79:in `check_via': You should not use the `match` method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action" (ArgumentError)

**Comment by mices** [comment]
Here's what happens in Rails 4.2
/.rvm/gems/ruby-2.3.3/gems/railties-4.2.10/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `load_defaults' for #<Rails::Application::Configuration:0x000000034e11c0> (NoMethodError)

**Comment by Bodacious** [comment]
@mices Sorry, but we won't be able to look into these issues for at least a week. If you're happy to wait, I'll get back to you as soon as I can

**Comment by pallavsharma** [comment]
any updates on this?
